-- Add version, audit and soft delete columns to all tables

-- Users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Cinemas table
ALTER TABLE cinemas ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE cinemas ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cinemas ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE cinemas ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cinemas ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE cinemas ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Halls table
ALTER TABLE halls ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE halls ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE halls ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE halls ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE halls ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE halls ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Seats table
ALTER TABLE seats ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE seats ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE seats ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE seats ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE seats ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE seats ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Movies table
ALTER TABLE movies ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Shows table
ALTER TABLE shows ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE shows ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE shows ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE shows ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE shows ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE shows ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Show_seats table
ALTER TABLE show_seats ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE show_seats ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE show_seats ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE show_seats ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE show_seats ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE show_seats ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Bookings table
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Payments table
ALTER TABLE payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Create indexes for soft delete queries
CREATE INDEX IF NOT EXISTS idx_users_deleted ON users(deleted);
CREATE INDEX IF NOT EXISTS idx_cinemas_deleted ON cinemas(deleted);
CREATE INDEX IF NOT EXISTS idx_halls_deleted ON halls(deleted);
CREATE INDEX IF NOT EXISTS idx_seats_deleted ON seats(deleted);
CREATE INDEX IF NOT EXISTS idx_movies_deleted ON movies(deleted);
CREATE INDEX IF NOT EXISTS idx_shows_deleted ON shows(deleted);
CREATE INDEX IF NOT EXISTS idx_show_seats_deleted ON show_seats(deleted);
CREATE INDEX IF NOT EXISTS idx_bookings_deleted ON bookings(deleted);
CREATE INDEX IF NOT EXISTS idx_payments_deleted ON payments(deleted);

COMMENT ON COLUMN users.version IS 'Optimistic locking version';
COMMENT ON COLUMN users.deleted IS 'Soft delete flag';
